### ISSUE TITLE
Fatal error: Can't use method return value in write context

### ISSUE THREAD

**Issue by chrisaldrich** [tinokremer/KnownJournal#2]
When I tried to post my first journal post, I received the following error: 

`**Fatal error**: Can't use method return value in write context in /htdocs/idno/IdnoPlugins/Journal/templates/default/entity/Journal.tpl.php on line 19`

The error seemed to bork the whole site and I had to uninstall to get things back to normal. Running the most recent stable version of Known (v0.9.1).

**Comment by tinokremer** [comment]
@chrisaldrich, are you on an older version of PHP, pre 5.5?

**Comment by chrisaldrich** [comment]
*facepalm* I was running it on an older server that didn't have a php version set which likely means that it was either at 5.5, 5.4, or possibly even older. Updating seems to have squared away the problem.  Thanks Tino! (And excellent little plugin by the way...)  I've had a few other quirky problems lately and with any luck, updating will also fix those.

**Comment by tinokremer** [comment]
Good to know it's fixed. I use my Journal plugin every day :)
